<div class="footer-top">
      <h1>Information</h1>
    </div>

    <!-- BODY FOOTER -->
    <footer>
      <div class="footer-body">
        <div class="footer-content">
          <h3>Quick Action</h3>
          <ul class="footer-ul">
            <li class="footer-li"><a href="index.php">Home</a></li>
            <li class="footer-li"><a href="product.php">Product</a></li>
            <li class="footer-li"><a href="enquire.php">Enquiry</a></li>
            <li class="footer-li"><a href="about.php">About us</a></li>
            <li class="footer-li">
              <a href="enhancements2.php">Enhancement</a>
            </li>
          </ul>
        </div>

        <div class="footer-content">
          <h3>Members</h3>
          <ul class="footer-ul">
            <li class="footer-li"><a href="about.php#TMinh">Thanh Minh</a></li>
            <li class="footer-li"><a href="about.php#NPhat">Nghia Phat</a></li>
            <li class="footer-li"><a href="about.php#QDanh">Quang Danh</a></li>
            <li class="footer-li"><a href="about.php#DThinh">Duc Thinh</a></li>
            <li class="footer-li"><a href="about.php#MKha">Minh Kha</a></li>
          </ul>
        </div>

        <div class="footer-content">
          <h3>For More Detail</h3>
          <ul class="footer-ul">
            <li class="footer-li">
              <a href="https://www.youtube.com/watch?v=5ZGT9jNfpVc">Assign 1 Video </a>
            </li>
            <li class="footer-li">
              <a href="https://youtu.be/UJa-xS61quk">Assign 2 Video </a>
            </li>
          </ul>
        </div>
      </div>
    </footer>

    <!-- BOTTOM FOOTER -->
    <div class="footer-bottom">
      <p>
        Copyright &copy; 2023 All Right Reserved <br >
        Swinburne Unversity of Technology - COS10026 - Computer Technology
        Inquiry Project
      </p>
    </div>